# "Copyright Advanced Micro Devices, Inc.
# Licensed under the Apache License Version 2.0"

#############################################################################
ARG BASE_IMAGE=rocm/dgl:latest
FROM ${BASE_IMAGE} AS dgl

SHELL ["/bin/bash", "--login", "-c"]
ENV DGL_SRC_DIR="/src/dgl"
ENV DEEP_LEARNING_EXAMPLES="/src/DeepLearningExamples"

# Set the default command to an interactive bash shell.
COPY . ${DEEP_LEARNING_EXAMPLES}

WORKDIR ${DEEP_LEARNING_EXAMPLES}
RUN pip install -r requirements.txt && pip install -e .
ENV LD_LIBRARY_PATH="/src/dgl/build/:${LD_LIBRARY_PATH}"


RUN pip install jupyter jupyterlab plotly torchinfo rdkit py3Dmol
#Run JupyterLab
#CMD ["jupyter", "lab", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root"]
